server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xs15072226372/microservicecloud-config.git #github上面git的仓库名字
          username: xs15072226372
          password: xueshuang15072226372



