spring:
  profiles:
    active:
    - dev
---
server:
  port: 8888
spring:
  profiles: dev
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
